cart/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(_('add/<product_id>/'), views.cart_add, name='cart_add'),
    path(_('remove/<product_id>/'), views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'shop'

urlpatterns = [
    path('', views.catalog, name='product_list'),
    path('<int:pk>', views.catalog, name='product_list'),
    path(_('item/<int:pk>'), views.detail, name='product'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields

class Category(TranslatableModel):
    #name = models.CharField(max_length=200, db_index=True)
    #slug = models.SlugField(max_length=200, db_index=True, unique=True)

    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True, unique=True)
    )

    class Meta:
        #ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list', kwargs={"pk": self.pk})
    
class Product(TranslatableModel):
    category = models.ForeignKey(Category, models.CASCADE, related_name='products')
    #name = models.CharField(max_length=200, db_index=True)
    #slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    #description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True),
        description=models.TextField(blank=True)
    )

    class Meta:
        ordering = ('-created',)
        #index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product', kwargs={"pk": self.pk})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm

def catalog(request, pk = None):
    if pk is None:
        category = None
        products = Product.objects.all()
    else:
        category = get_object_or_404(Category, pk = pk)
        products = Product.objects.filter(category = category)

    return render(request, 'shop/product/list.html', 
    {
        'category': category,
        'categories': Category.objects.all(),
        'products': products,
    })

def detail(request, pk):
    product = get_object_or_404(Product, pk = pk, available = True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', 
    {
        'product': product,
        'cart_product_form': cart_product_form
    })

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="{% trans "Add to cart" %}">
    </form>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>{% trans "Categories" %}</h3>
    <ul class="categories">
        <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url "shop:product_list" %}">{% trans "All" %}</a>
        </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
<h1>{% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}</h1>
<div id="main" class="product-list">
    {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <div class="item-image" style="background-image: url({% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %})">
                </div>
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            ${{ product.price }}
        </div>
    {% endfor %}
</div>
{% endblock %}