cart/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(_('add/<product_id>/'), views.cart_add, name='cart_add'),
    path(_('remove/<product_id>/'), views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'shop'

urlpatterns = [
    path('', views.catalog, name='product_list'),
    path('<int:pk>', views.catalog, name='product_list'),
    path(_('item/<int:pk>'), views.detail, name='product'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields

class Category(TranslatableModel):
    #name = models.CharField(max_length=200, db_index=True)
    #slug = models.SlugField(max_length=200, db_index=True, unique=True)

    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True, unique=True)
    )

    class Meta:
        #ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list', kwargs={"pk": self.pk})
    
class Product(TranslatableModel):
    category = models.ForeignKey(Category, models.CASCADE, related_name='products')
    #name = models.CharField(max_length=200, db_index=True)
    #slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    #description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True),
        description=models.TextField(blank=True)
    )

    class Meta:
        ordering = ('-created',)
        #index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product', kwargs={"pk": self.pk})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm

def catalog(request, pk = None):
    if pk is None:
        category = None
        products = Product.objects.all()
    else:
        category = get_object_or_404(Category, pk = pk)
        products = Product.objects.filter(category = category)

    return render(request, 'shop/product/list.html', 
    {
        'category': category,
        'categories': Category.objects.all(),
        'products': products,
    })

def detail(request, pk):
    product = get_object_or_404(Product, pk = pk, available = True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', 
    {
        'product': product,
        'cart_product_form': cart_product_form
    })

shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}{% trans "My shop" %}{% endblock %}
    </title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <nav id="navbar">
            <a href="/" class="logo">Toys shop</a>

            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <div class="languages">
                <p>{% trans "Language" %}:</p>
                <ul class="languages">
                    {% for language in languages %}
                        <li>
                            <a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                                {{ language.name_local }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        {% trans "Your cart" %}:
                        <a href="{% url "cart:cart_detail" %}">
                            {% blocktrans with total_items_plural=total_items|pluralize total_price=cart.get_total_price %}
                                {{ total_items }} item{{ total_items_plural }},
                                ${{ total_price }}
                            {% endblocktrans %}
                        </a>
                    {% else %}
                        {% trans "Your cart is empty." %}
                    {% endif %}
                {% endwith %}
            </div>
        </nav>
    </div>
    <main id="content">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>